#define PJ_CONFIG_IPHONE 1
#define PJ_IPHONE_OS_HAS_MULTITASKING_SUPPORT 1
#define PJ_ACTIVESOCK_TCP_IPHONE_OS_BG 0
#define PJ_HAS_TCP 1
#define PJMEDIA_VIDEO_DEV_HAS_FFMPEG  1
#define PJSIP_UDP_SIZE_THRESHOLD 6000
#define PJSIP_DONT_SWITCH_TO_TCP 1
#define PJSIP_MAX_URL_SIZE 512
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_HAS_OPENH264_CODEC 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL_ES 1
#define PJMEDIA_VIDEO_DEV_HAS_IOS_OPENGL 1
#include <OpenGLES/ES3/glext.h>
 #define PJ_HAS_IPV6 1
#include <VialerPJSIP/pj/config_site_sample.h>
